---
image: circleci/ruby:3.0.3-node-browsers

variables:

before_script:
  - bundle config mirror.https://rubygems.org https://gems.ruby-china.com
  - bundle config set path 'vendor'  # Install dependencies into ./vendor/ruby

stages:
  - test

test:
  stage: test
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby
    - key:
        files:
          - yarn.lock
      paths:
        - ".yarn-cache/"
  script:
    - bundle install -j $(nproc)
    - yarn install --cache-folder .yarn-cache
    - cp config/database.yml.sample config/database.yml
    - echo $RAILS_MASTER_KEY > config/master.key
    - bundle exec rails db:schema:load --trace
    - bundle exec rails test
